# devsetup/templates/docker/docker-compose.yml
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ${PROJECT_NAME}_app
    volumes:
      - ./src:/var/www
    ports:
      - "${PORT}:9000"
    networks:
      - dev-network

  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - dev-network

  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${PROJECT_NAME}_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
