services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: 
      DB_USERNAME: 
      DB_PASSWORD: 


  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    container_name: mysql
    image: mysql:8.0
    ports:
      - ":3306"
    environment:
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
